name: Test HTML File

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-html:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install HTML Validator
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy

      - name: Validate HTML
        run: |
          tidy -errors -quiet -utf8 index.html
